# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190111_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='features',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
