# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190112_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='features',
            name='created_by',
        ),
    ]
